source "https://github.com/CocoaPods/Specs.git"

platform :ios, “13.0”
use_frameworks!
target ‘GHMoyaNetWorkTest’ do
pod 'Moya', '~> 14.0'
pod 'SwiftyJSON'
#pod 'HandyJSON', '~> 5.0.2-beta'
pod 'ObjectMapper'
end
